version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ECR_REGISTRY: 701699495666.dkr.ecr.us-east-1.amazonaws.com
    ECR_REPOSITORY_URI: 701699495666.dkr.ecr.us-east-1.amazonaws.com/test-ecr
    IMAGE_NAME: container-test-app
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws sts get-caller-identity
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_REPOSITORY_URI}:${IMAGE_TAG}

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ${ECR_REPOSITORY_URI}:${IMAGE_TAG}
      - echo Build completed on `date`
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"container-test-app","imageUri":"%s"}]' ${ECR_REPOSITORY_URI}:${IMAGE_TAG} > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
